# basic dependabot config file.
#
# Announcement: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
# Documentation: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically
#     (Do not refer to documentation on https://dependabot.com/docs/config-file/ not compatible with GitHub).
#

version: 2
updates:
    - package-ecosystem: "maven"
      directories:
          - "/"
          - "/backend"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/frontend"
      schedule:
          interval: "daily"
      ignore:
          - dependency-name: "@technical-design/ripe-app-webcomponents"
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "daily"
