server:
    port: 8443
    ssl:
        key-store: 'classpath:keystore'
        key-store-password: OBF:1v2j1uum1xtv1zej1zer1xtn1uvk1v1v
spring:
    profiles:
        active: dev

rest:
    api:
        ripeUrl:  https://rest-dev.db.ripe.net

ripe:
    search:
           queryUrl: https://dev.db.ripe.net/search/query.html

internal:
    api:
        url: http://int-dev.db.ripe.net
        key: DB-WHOIS-d5395e7fbf8d

crowd:
    rest:
        url: http://serval.prepdev.ripe.net:8095/crowd
        user: db
        password: evarylli
    login:
        url: https://access.prepdev.ripe.net/

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
