server:
    port: 8443
    ssl:
        key-store: 'classpath:keystore'
        key-store-password: OBF:1v2j1uum1xtv1zej1zer1xtn1uvk1v1v
spring:
    profiles:
        active: dev

rest:
    api:
        ripeUrl: http://db-dev-1.dev.ripe.net:1080/whois

internal:
    api:
        url: http://int-dev.db.ripe.net
        key: DB-WHOIS-d5395e7fbf8d

# SSO translation properties
crowd:
    rest:
        url: http://serval.prepdev.ripe.net:8095/crowd
        user: db
        password: evarylli


