server:
    port: 8443
    ssl:
        key-store: 'classpath:keystore'
        key-store-password: OBF:1v2j1uum1xtv1zej1zer1xtn1uvk1v1v
spring:
    profiles:
        active: dev

rest:
    api:
       ripeUrl: http://localhost:1080/whois


