spring:
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        client-id: ripe-db-web-ui
                        client-secret: ITGQOq4VwIfEh97GnXTajcvgDlLsyhED
                        scope:
                            - openid
                            - profile
                            - email

                provider:
                    keycloak:

                        issuer-uri: https://idp.acc.ripe.net/realms/ripe-ncc
