---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - "java.lang:type=OperatingSystem"
  - "com.hazelcast:type=Metrics,*"
blacklistObjectNames: []
rules:
  - pattern: "java.lang<type=OperatingSystem><>(committed_virtual_memory|free_physical_memory|free_swap_space|total_physical_memory|total_swap_space)_size:"
    name: os_$1_bytes
    type: GAUGE
    attrNameSnakeCase: true
  - pattern: 'java.lang<type=OperatingSystem><>((?!process_cpu_time)\w+):'
    name: os_$1
    type: GAUGE
    attrNameSnakeCase: true

  # Hazelcast data structures (map, cache, queue, etc) tagged by name: tag0="name=xyz"
  - pattern: 'com\.hazelcast<type=Metrics, instance=(.*), prefix=(.*), tag0="name=(.*)"><>(.+):'
    name: hz_$2_$4
    labels:
      name: "$3"
    type: GAUGE
    attrNameSnakeCase: true

  # Hazelcast metrics with a name-tagged plus a second tag (e.g. per-partition, per-member)
  - pattern: 'com\.hazelcast<type=Metrics, instance=(.*), prefix=(.*), tag0="name=(.*)", tag1=(.*)><>(.+):'
    name: hz_$2_$5
    labels:
      name: "$3"
      tag1: "$4"
    type: GAUGE
    attrNameSnakeCase: true

  # Hazelcast metrics with no name tag (JVM, cluster, GC-level stats)
  - pattern: 'com\.hazelcast<type=Metrics, instance=(.*), prefix=(.*)><>(.+):'
    name: hz_$2_$3
    type: GAUGE
    attrNameSnakeCase: true