swagger: '2.0'
info:
  title: Domain Object API
  description: Provides batch creation and updates of domain objects
  version: "1.0.0"

host: api.ripe.net

schemes:
  - https
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /domain-objects:
    post:
      summary: Domain Objects
      parameters:
        - name: objects
          in: body
          required: true
          schema:
               $ref: '#/definitions/DomainObject'
      responses:
        200:
          description: An array of domain objects
          schema:
            type: array
            items:
              $ref: '#/definitions/DomainObject'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  DomainObject:
    type: object
    properties:
      prefix:
        type: string
        description: e.g. 10.10.0.0/22
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
