'use strict';

angular.module('dbWebApp')
    .service('CountryCodes', ['$log', function ($log) {
        var countryCodes = [
            {"key": "AD", "value": "Andorra"},
            {"key": "AE", "value": "United Arab Emirates"},
            {"key": "AF", "value": "Afghanistan"},
            {"key": "AG", "value": "Antigua and Barbuda"},
            {"key": "AI", "value": "Anguilla"},
            {"key": "AM", "value": "Armenia"},
            {"key": "AQ", "value": "Antarctica"},
            {"key": "AS", "value": "American Samoa"},
            {"key": "AU", "value": "Australia"},
            {"key": "AX", "value": "Åland Islands"},
            {"key": "BA", "value": "Bosnia and Herzegovina"},
            {"key": "BD", "value": "Bangladesh"},
            {"key": "BE", "value": "Belgium"},
            {"key": "BF", "value": "Burkina Faso"},
            {"key": "BH", "value": "Bahrain"},
            {"key": "BJ", "value": "Benin"},
            {"key": "BM", "value": "Bermuda"},
            {"key": "BO", "value": "Bolivia, Plurinational State of"},
            {"key": "BR", "value": "Brazil"},
            {"key": "BT", "value": "Bhutan"},
            {"key": "BW", "value": "Botswana"},
            {"key": "BZ", "value": "Belize"},
            {"key": "CC", "value": "Cocos (Keeling) Islands"},
            {"key": "CF", "value": "Central African Republic"},
            {"key": "CH", "value": "Switzerland"},
            {"key": "CK", "value": "Cook Islands"},
            {"key": "CM", "value": "Cameroon"},
            {"key": "CO", "value": "Colombia"},
            {"key": "CU", "value": "Cuba"},
            {"key": "CW", "value": "Curaçao"},
            {"key": "CY", "value": "Cyprus"},
            {"key": "DE", "value": "Germany"},
            {"key": "DK", "value": "Denmark"},
            {"key": "DO", "value": "Dominican Republic"},
            {"key": "EC", "value": "Ecuador"},
            {"key": "EG", "value": "Egypt"},
            {"key": "ER", "value": "Eritrea"},
            {"key": "ET", "value": "Ethiopia"},
            {"key": "FJ", "value": "Fiji"},
            {"key": "FM", "value": "Micronesia, Federated States of"},
            {"key": "FR", "value": "France"},
            {"key": "GB", "value": "United Kingdom"},
            {"key": "GE", "value": "Georgia"},
            {"key": "GG", "value": "Guernsey"},
            {"key": "GI", "value": "Gibraltar"},
            {"key": "GM", "value": "Gambia"},
            {"key": "GP", "value": "Guadeloupe"},
            {"key": "GR", "value": "Greece"},
            {"key": "GT", "value": "Guatemala"},
            {"key": "GW", "value": "Guinea-Bissau"},
            {"key": "HK", "value": "Hong Kong"},
            {"key": "HN", "value": "Honduras"},
            {"key": "HT", "value": "Haiti"},
            {"key": "ID", "value": "Indonesia"},
            {"key": "IL", "value": "Israel"},
            {"key": "IN", "value": "India"},
            {"key": "IQ", "value": "Iraq"},
            {"key": "IS", "value": "Iceland"},
            {"key": "JE", "value": "Jersey"},
            {"key": "JO", "value": "Jordan"},
            {"key": "KE", "value": "Kenya"},
            {"key": "KH", "value": "Cambodia"},
            {"key": "KM", "value": "Comoros"},
            {"key": "KP", "value": "Korea, Democratic People's Republic of"},
            {"key": "KW", "value": "Kuwait"},
            {"key": "KZ", "value": "Kazakhstan"},
            {"key": "LB", "value": "Lebanon"},
            {"key": "LI", "value": "Liechtenstein"},
            {"key": "LR", "value": "Liberia"},
            {"key": "LT", "value": "Lithuania"},
            {"key": "LV", "value": "Latvia"},
            {"key": "MA", "value": "Morocco"},
            {"key": "MD", "value": "Moldova, Republic of"},
            {"key": "MF", "value": "Saint Martin (French part)"},
            {"key": "MH", "value": "Marshall Islands"},
            {"key": "ML", "value": "Mali"},
            {"key": "MN", "value": "Mongolia"},
            {"key": "MP", "value": "Northern Mariana Islands"},
            {"key": "MR", "value": "Mauritania"},
            {"key": "MT", "value": "Malta"},
            {"key": "MV", "value": "Maldives"},
            {"key": "MW", "value": "Malawi"},
            {"key": "MY", "value": "Malaysia"},
            {"key": "NA", "value": "Namibia"},
            {"key": "NE", "value": "Niger"},
            {"key": "NG", "value": "Nigeria"},
            {"key": "NL", "value": "Netherlands"},
            {"key": "NP", "value": "Nepal"},
            {"key": "NU", "value": "Niue"},
            {"key": "OM", "value": "Oman"},
            {"key": "PE", "value": "Peru"},
            {"key": "PG", "value": "Papua New Guinea"},
            {"key": "PK", "value": "Pakistan"},
            {"key": "PM", "value": "Saint Pierre and Miquelon"},
            {"key": "PR", "value": "Puerto Rico"},
            {"key": "PT", "value": "Portugal"},
            {"key": "PY", "value": "Paraguay"},
            {"key": "RE", "value": "Réunion"},
            {"key": "RS", "value": "Serbia"},
            {"key": "SA", "value": "Saudi Arabia"},
            {"key": "SC", "value": "Seychelles"},
            {"key": "SE", "value": "Sweden"},
            {"key": "SH", "value": "Saint Helena, Ascension and Tristan da Cunha"},
            {"key": "SJ", "value": "Svalbard and Jan Mayen"},
            {"key": "SL", "value": "Sierra Leone"},
            {"key": "SN", "value": "Senegal"},
            {"key": "SR", "value": "Suriname"},
            {"key": "ST", "value": "Sao Tome and Principe"},
            {"key": "SX", "value": "Sint Maarten (Dutch part)"},
            {"key": "SZ", "value": "Swaziland"},
            {"key": "TD", "value": "Chad"},
            {"key": "TG", "value": "Togo"},
            {"key": "TJ", "value": "Tajikistan"},
            {"key": "TL", "value": "Timor-Leste"},
            {"key": "TN", "value": "Tunisia"},
            {"key": "TR", "value": "Turkey"},
            {"key": "TV", "value": "Tuvalu"},
            {"key": "TZ", "value": "Tanzania, United Republic of"},
            {"key": "UG", "value": "Uganda"},
            {"key": "US", "value": "United States"},
            {"key": "UZ", "value": "Uzbekistan"},
            {"key": "VC", "value": "Saint Vincent and the Grenadines"},
            {"key": "VG", "value": "Virgin Islands, British"},
            {"key": "VN", "value": "Viet Nam"},
            {"key": "WF", "value": "Wallis and Futuna"},
            {"key": "YE", "value": "Yemen"},
            {"key": "ZA", "value": "South Africa"},
            {"key": "ZW", "value": "Zimbabwe"},
        ];

        this.get = function () {
            return countryCodes;
        }

    }]);
