'use strict';

angular.module('dbWebApp')
    .service('CountryCodes', ['$log', function ($log) {
        var countryCodes = [
            {"key": "VA", "value": "Vatican"},
            {"key": "AW", "value": "Aruba"},
            {"key": "TN", "value": "Tunisia"},
            {"key": "MC", "value": "Monaco"},
            {"key": "SD", "value": "Sudan"},
            {"key": "TC", "value": "Turks and Caicos Islands"},
            {"key": "AL", "value": "Albania"},
            {"key": "PL", "value": "Poland"},
            {"key": "LT", "value": "Lithuania"},
            {"key": "LU", "value": "Luxembourg"},
            {"key": "TH", "value": "Thailand"},
            {"key": "PA", "value": "Panama"},
            {"key": "PK", "value": "Pakistan"},
            {"key": "YE", "value": "Yemen"},
            {"key": "BG", "value": "Bulgaria"},
            {"key": "SN", "value": "Senegal"},
            {"key": "PT", "value": "Portugal"},
            {"key": "ML", "value": "Mali"},
            {"key": "MP", "value": "Northern Mariana Islands"},
            {"key": "SZ", "value": "Swaziland"},
            {"key": "BI", "value": "Burundi"},
            {"key": "GM", "value": "Gambia"},
            {"key": "PR", "value": "Puerto Rico"},
            {"key": "FK", "value": "Falkland Islands"},
            {"key": "CN", "value": "China"},
            {"key": "KY", "value": "Cayman Islands"},
            {"key": "TK", "value": "Tokelau"},
            {"key": "HK", "value": "Hong Kong"},
            {"key": "SO", "value": "Somalia"},
            {"key": "EG", "value": "Egypt"},
            {"key": "US", "value": "United States"},
            {"key": "PN", "value": "Pitcairn"},
            {"key": "VC", "value": "Saint Vincent and the Grenadines"},
            {"key": "BQ", "value": "Bonaire, Saint Eustatius and Saba"},
            {"key": "MK", "value": "Macedonia"},
            {"key": "TV", "value": "Tuvalu"},
            {"key": "RE", "value": "Reunion"},
            {"key": "FR", "value": "France"},
            {"key": "CX", "value": "Christmas Island"},
            {"key": "KP", "value": "North Korea"},
            {"key": "DO", "value": "Dominican Republic"},
            {"key": "TW", "value": "Taiwan"},
            {"key": "IS", "value": "Iceland"},
            {"key": "GT", "value": "Guatemala"},
            {"key": "PE", "value": "Peru"},
            {"key": "FM", "value": "Micronesia"},
            {"key": "IN", "value": "India"},
            {"key": "SG", "value": "Singapore"},
            {"key": "MZ", "value": "Mozambique"},
            {"key": "BT", "value": "Bhutan"},
            {"key": "GP", "value": "Guadeloupe"},
            {"key": "MY", "value": "Malaysia"},
            {"key": "BM", "value": "Bermuda"},
            {"key": "AI", "value": "Anguilla"},
            {"key": "QA", "value": "Qatar"},
            {"key": "SS", "value": "South Sudan"},
            {"key": "WS", "value": "Samoa"},
            {"key": "HN", "value": "Honduras"},
            {"key": "VU", "value": "Vanuatu"},
            {"key": "FO", "value": "Faroe Islands"},
            {"key": "TR", "value": "Turkey"},
            {"key": "BH", "value": "Bahrain"},
            {"key": "BS", "value": "Bahamas"},
            {"key": "FJ", "value": "Fiji"},
            {"key": "MS", "value": "Montserrat"},
            {"key": "CH", "value": "Switzerland"},
            {"key": "AD", "value": "Andorra"},
            {"key": "GA", "value": "Gabon"},
            {"key": "EC", "value": "Ecuador"},
            {"key": "MA", "value": "Morocco"},
            {"key": "MM", "value": "Myanmar"},
            {"key": "TZ", "value": "Tanzania"},
            {"key": "SH", "value": "Saint Helena"},
            {"key": "SX", "value": "Sint Maarten"},
            {"key": "LA", "value": "Laos"},
            {"key": "BL", "value": "Saint Barthelemy"},
            {"key": "RS", "value": "Serbia"},
            {"key": "MG", "value": "Madagascar"},
            {"key": "AQ", "value": "Antarctica"},
            {"key": "BZ", "value": "Belize"},
            {"key": "ZW", "value": "Zimbabwe"},
            {"key": "KH", "value": "Cambodia"},
            {"key": "GD", "value": "Grenada"},
            {"key": "AM", "value": "Armenia"},
            {"key": "GW", "value": "Guinea-Bissau"},
            {"key": "NO", "value": "Norway"},
            {"key": "PH", "value": "Philippines"},
            {"key": "AR", "value": "Argentina"},
            {"key": "BV", "value": "Bouvet Island"},
            {"key": "ER", "value": "Eritrea"},
            {"key": "DK", "value": "Denmark"},
            {"key": "BB", "value": "Barbados"},
            {"key": "SA", "value": "Saudi Arabia"},
            {"key": "NA", "value": "Namibia"},
            {"key": "UY", "value": "Uruguay"},
            {"key": "TT", "value": "Trinidad and Tobago"},
            {"key": "AO", "value": "Angola"},
            {"key": "IL", "value": "Israel"},
            {"key": "KM", "value": "Comoros"},
            {"key": "KZ", "value": "Kazakhstan"},
            {"key": "JP", "value": "Japan"},
            {"key": "IQ", "value": "Iraq"},
            {"key": "VN", "value": "Vietnam"},
            {"key": "SB", "value": "Solomon Islands"},
            {"key": "MH", "value": "Marshall Islands"},
            {"key": "CZ", "value": "Czech Republic"},
            {"key": "KW", "value": "Kuwait"},
            {"key": "SV", "value": "El Salvador"},
            {"key": "PM", "value": "Saint Pierre and Miquelon"},
            {"key": "IT", "value": "Italy"},
            {"key": "HR", "value": "Croatia"},
            {"key": "HT", "value": "Haiti"},
            {"key": "MF", "value": "Saint Martin"},
            {"key": "UZ", "value": "Uzbekistan"},
            {"key": "CO", "value": "Colombia"},
            {"key": "BR", "value": "Brazil"},
            {"key": "GY", "value": "Guyana"},
            {"key": "GL", "value": "Greenland"},
            {"key": "VG", "value": "British Virgin Islands"},
            {"key": "CU", "value": "Cuba"},
            {"key": "ST", "value": "Sao Tome and Principe"},
            {"key": "GG", "value": "Guernsey"},
            {"key": "PF", "value": "French Polynesia"},
            {"key": "ZA", "value": "South Africa"},
            {"key": "FI", "value": "Finland"},
            {"key": "YT", "value": "Mayotte"},
            {"key": "TO", "value": "Tonga"},
            {"key": "AG", "value": "Antigua and Barbuda"},
            {"key": "JE", "value": "Jersey"},
            {"key": "RU", "value": "Russia"},
            {"key": "MQ", "value": "Martinique"},
            {"key": "NZ", "value": "New Zealand"},
            {"key": "ES", "value": "Spain"},
            {"key": "MW", "value": "Malawi"},
            {"key": "MR", "value": "Mauritania"},
            {"key": "ID", "value": "Indonesia"},
            {"key": "PW", "value": "Palau"},
            {"key": "MO", "value": "Macao"},
            {"key": "LI", "value": "Liechtenstein"},
            {"key": "MN", "value": "Mongolia"},
            {"key": "NL", "value": "Netherlands"},
            {"key": "CL", "value": "Chile"},
            {"key": "KG", "value": "Kyrgyzstan"},
            {"key": "SR", "value": "Suriname"},
            {"key": "BO", "value": "Bolivia"},
            {"key": "BJ", "value": "Benin"},
            {"key": "SJ", "value": "Svalbard and Jan Mayen"},
            {"key": "KI", "value": "Kiribati"},
            {"key": "IE", "value": "Ireland"},
            {"key": "GU", "value": "Guam"},
            {"key": "KN", "value": "Saint Kitts and Nevis"},
            {"key": "DJ", "value": "Djibouti"},
            {"key": "XK", "value": "Kosovo"},
            {"key": "AX", "value": "Aland Islands"},
            {"key": "RW", "value": "Rwanda"},
            {"key": "CM", "value": "Cameroon"},
            {"key": "AF", "value": "Afghanistan"},
            {"key": "MT", "value": "Malta"},
            {"key": "CW", "value": "Curacao"},
            {"key": "SI", "value": "Slovenia"},
            {"key": "LK", "value": "Sri Lanka"},
            {"key": "AS", "value": "American Samoa"},
            {"key": "WF", "value": "Wallis and Futuna"},
            {"key": "BW", "value": "Botswana"},
            {"key": "MU", "value": "Mauritius"},
            {"key": "SL", "value": "Sierra Leone"},
            {"key": "LR", "value": "Liberia"},
            {"key": "MV", "value": "Maldives"},
            {"key": "DZ", "value": "Algeria"},
            {"key": "UA", "value": "Ukraine"},
            {"key": "BA", "value": "Bosnia and Herzegovina"},
            {"key": "GF", "value": "French Guiana"},
            {"key": "GN", "value": "Guinea"},
            {"key": "AZ", "value": "Azerbaijan"},
            {"key": "NR", "value": "Nauru"},
            {"key": "KR", "value": "South Korea"},
            {"key": "SM", "value": "San Marino"},
            {"key": "SK", "value": "Slovakia"},
            {"key": "GH", "value": "Ghana"},
            {"key": "PY", "value": "Paraguay"},
            {"key": "MD", "value": "Moldova"},
            {"key": "SY", "value": "Syria"},
            {"key": "GR", "value": "Greece"},
            {"key": "NI", "value": "Nicaragua"},
            {"key": "BY", "value": "Belarus"},
            {"key": "TL", "value": "East Timor"},
            {"key": "RO", "value": "Romania"},
            {"key": "EE", "value": "Estonia"},
            {"key": "NU", "value": "Niue"},
            {"key": "DM", "value": "Dominica"},
            {"key": "BN", "value": "Brunei"},
            {"key": "TD", "value": "Chad"},
            {"key": "ZM", "value": "Zambia"},
            {"key": "LC", "value": "Saint Lucia"},
            {"key": "ME", "value": "Montenegro"},
            {"key": "CA", "value": "Canada"},
            {"key": "KE", "value": "Kenya"},
            {"key": "NP", "value": "Nepal"},
            {"key": "CR", "value": "Costa Rica"},
            {"key": "BE", "value": "Belgium"},
            {"key": "VI", "value": "U.S. Virgin Islands"},
            {"key": "IR", "value": "Iran"},
            {"key": "LB", "value": "Lebanon"},
            {"key": "AE", "value": "United Arab Emirates"},
            {"key": "VE", "value": "Venezuela"},
            {"key": "UG", "value": "Uganda"},
            {"key": "OM", "value": "Oman"},
            {"key": "CF", "value": "Central African Republic"},
            {"key": "UM", "value": "United States Minor Outlying Islands"},
            {"key": "GQ", "value": "Equatorial Guinea"},
            {"key": "GB", "value": "United Kingdom"},
            {"key": "GI", "value": "Gibraltar"},
            {"key": "GE", "value": "Georgia"},
            {"key": "CI", "value": "Ivory Coast"},
            {"key": "TF", "value": "French Southern Territories"},
            {"key": "IM", "value": "Isle of Man"},
            {"key": "MX", "value": "Mexico"},
            {"key": "NF", "value": "Norfolk Island"},
            {"key": "CV", "value": "Cape Verde"},
            {"key": "TJ", "value": "Tajikistan"},
            {"key": "PS", "value": "Palestinian Territory"},
            {"key": "ET", "value": "Ethiopia"},
            {"key": "BF", "value": "Burkina Faso"},
            {"key": "HU", "value": "Hungary"},
            {"key": "LY", "value": "Libya"},
            {"key": "BD", "value": "Bangladesh"},
            {"key": "JO", "value": "Jordan"},
            {"key": "CG", "value": "Republic of the Congo"},
            {"key": "CD", "value": "Democratic Republic of the Congo"},
            {"key": "SE", "value": "Sweden"},
            {"key": "DE", "value": "Germany"},
            {"key": "LV", "value": "Latvia"},
            {"key": "JM", "value": "Jamaica"},
            {"key": "TM", "value": "Turkmenistan"},
            {"key": "HM", "value": "Heard Island and McDonald Islands"},
            {"key": "NE", "value": "Niger"},
            {"key": "AT", "value": "Austria"},
            {"key": "EH", "value": "Western Sahara"},
            {"key": "CY", "value": "Cyprus"},
            {"key": "PG", "value": "Papua New Guinea"},
            {"key": "IO", "value": "British Indian Ocean Territory"},
            {"key": "CK", "value": "Cook Islands"},
            {"key": "NC", "value": "New Caledonia"},
            {"key": "SC", "value": "Seychelles"},
            {"key": "AU", "value": "Australia"},
            {"key": "LS", "value": "Lesotho"},
            {"key": "TG", "value": "Togo"},
            {"key": "GS", "value": "South Georgia and the South Sandwich Islands"},
            {"key": "NG", "value": "Nigeria"},
            {"key": "CC", "value": "Cocos Islands"},
        ];

        this.get = function () {
            return countryCodes;
        }

    }]);
