'use strict';

angular.module('dbWebApp')
    .service('LanguageCodes', ['$log', function ($log) {
        var languageCodes = [
            { "key":"ab", "value":"Abkhaz"},
            { "key":"aa", "value":"Afar"},
            { "key":"af", "value":"Afrikaans"},
            { "key":"ak", "value":"Akan"},
            { "key":"sq", "value":"Albanian"},
            { "key":"am", "value":"Amharic"},
            { "key":"ar", "value":"Arabic"},
            { "key":"an", "value":"Aragonese"},
            { "key":"hy", "value":"Armenian"},
            { "key":"as", "value":"Assamese"},
            { "key":"av", "value":"Avaric"},
            { "key":"ae", "value":"Avestan"},
            { "key":"ay", "value":"Aymara"},
            { "key":"az", "value":"Azerbaijani"},
            { "key":"bm", "value":"Bambara"},
            { "key":"ba", "value":"Bashkir"},
            { "key":"eu", "value":"Basque"},
            { "key":"be", "value":"Belarusian"},
            { "key":"bn", "value":"Bengali"},
            { "key":"bh", "value":"Bihari"},
            { "key":"bi", "value":"Bislama"},
            { "key":"bs", "value":"Bosnian"},
            { "key":"br", "value":"Breton"},
            { "key":"bg", "value":"Bulgarian"},
            { "key":"my", "value":"Burmese"},
            { "key":"ca", "value":"Catalan; Valencian"},
            { "key":"ch", "value":"Chamorro"},
            { "key":"ce", "value":"Chechen"},
            { "key":"ny", "value":"Chichewa; Chewa; Nyanja"},
            { "key":"zh", "value":"Chinese"},
            { "key":"cv", "value":"Chuvash"},
            { "key":"kw", "value":"Cornish"},
            { "key":"co", "value":"Corsican"},
            { "key":"cr", "value":"Cree"},
            { "key":"hr", "value":"Croatian"},
            { "key":"cs", "value":"Czech"},
            { "key":"da", "value":"Danish"},
            { "key":"dv", "value":"Divehi; Dhivehi; Maldivian;"},
            { "key":"nl", "value":"Dutch"},
            { "key":"en", "value":"English"},
            { "key":"eo", "value":"Esperanto"},
            { "key":"et", "value":"Estonian"},
            { "key":"ee", "value":"Ewe"},
            { "key":"fo", "value":"Faroese"},
            { "key":"fj", "value":"Fijian"},
            { "key":"fi", "value":"Finnish"},
            { "key":"fr", "value":"French"},
            { "key":"ff", "value":"Fula; Fulah; Pulaar; Pular"},
            { "key":"gl", "value":"Galician"},
            { "key":"ka", "value":"Georgian"},
            { "key":"de", "value":"German"},
            { "key":"el", "value":"Greek, Modern"},
            { "key":"gn", "value":"Guaraní"},
            { "key":"gu", "value":"Gujarati"},
            { "key":"ht", "value":"Haitian; Haitian Creole"},
            { "key":"ha", "value":"Hausa"},
            { "key":"he", "value":"Hebrew (modern)"},
            { "key":"hz", "value":"Herero"},
            { "key":"hi", "value":"Hindi"},
            { "key":"ho", "value":"Hiri Motu"},
            { "key":"hu", "value":"Hungarian"},
            { "key":"ia", "value":"Interlingua"},
            { "key":"id", "value":"Indonesian"},
            { "key":"ie", "value":"Interlingue"},
            { "key":"ga", "value":"Irish"},
            { "key":"ig", "value":"Igbo"},
            { "key":"ik", "value":"Inupiaq"},
            { "key":"io", "value":"Ido"},
            { "key":"is", "value":"Icelandic"},
            { "key":"it", "value":"Italian"},
            { "key":"iu", "value":"Inuktitut"},
            { "key":"ja", "value":"Japanese"},
            { "key":"jv", "value":"Javanese"},
            { "key":"kl", "value":"Kalaallisut, Greenlandic"},
            { "key":"kn", "value":"Kannada"},
            { "key":"kr", "value":"Kanuri"},
            { "key":"ks", "value":"Kashmiri"},
            { "key":"kk", "value":"Kazakh"},
            { "key":"km", "value":"Khmer"},
            { "key":"ki", "value":"Kikuyu, Gikuyu"},
            { "key":"rw", "value":"Kinyarwanda"},
            { "key":"ky", "value":"Kirghiz, Kyrgyz"},
            { "key":"kv", "value":"Komi"},
            { "key":"kg", "value":"Kongo"},
            { "key":"ko", "value":"Korean"},
            { "key":"ku", "value":"Kurdish"},
            { "key":"kj", "value":"Kwanyama, Kuanyama"},
            { "key":"la", "value":"Latin"},
            { "key":"lb", "value":"Luxembourgish, Letzeburgesch"},
            { "key":"lg", "value":"Luganda"},
            { "key":"li", "value":"Limburgish, Limburgan, Limburger"},
            { "key":"ln", "value":"Lingala"},
            { "key":"lo", "value":"Lao"},
            { "key":"lt", "value":"Lithuanian"},
            { "key":"lu", "value":"Luba-Katanga"},
            { "key":"lv", "value":"Latvian"},
            { "key":"gv", "value":"Manx"},
            { "key":"mk", "value":"Macedonian"},
            { "key":"mg", "value":"Malagasy"},
            { "key":"ms", "value":"Malay"},
            { "key":"ml", "value":"Malayalam"},
            { "key":"mt", "value":"Maltese"},
            { "key":"mi", "value":"Māori"},
            { "key":"mr", "value":"Marathi (Marāṭhī)"},
            { "key":"mh", "value":"Marshallese"},
            { "key":"mn", "value":"Mongolian"},
            { "key":"na", "value":"Nauru"},
            { "key":"nv", "value":"Navajo, Navaho"},
            { "key":"nb", "value":"Norwegian Bokmål"},
            { "key":"nd", "value":"North Ndebele"},
            { "key":"ne", "value":"Nepali"},
            { "key":"ng", "value":"Ndonga"},
            { "key":"nn", "value":"Norwegian Nynorsk"},
            { "key":"no", "value":"Norwegian"},
            { "key":"ii", "value":"Nuosu"},
            { "key":"nr", "value":"South Ndebele"},
            { "key":"oc", "value":"Occitan"},
            { "key":"oj", "value":"Ojibwe, Ojibwa"},
            { "key":"cu", "value":"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic"},
            { "key":"om", "value":"Oromo"},
            { "key":"or", "value":"Oriya"},
            { "key":"os", "value":"Ossetian, Ossetic"},
            { "key":"pa", "value":"Panjabi, Punjabi"},
            { "key":"pi", "value":"Pāli"},
            { "key":"fa", "value":"Persian"},
            { "key":"pl", "value":"Polish"},
            { "key":"ps", "value":"Pashto, Pushto"},
            { "key":"pt", "value":"Portuguese"},
            { "key":"qu", "value":"Quechua"},
            { "key":"rm", "value":"Romansh"},
            { "key":"rn", "value":"Kirundi"},
            { "key":"ro", "value":"Romanian, Moldavian, Moldovan"},
            { "key":"ru", "value":"Russian"},
            { "key":"sa", "value":"Sanskrit (Saṁskṛta)"},
            { "key":"sc", "value":"Sardinian"},
            { "key":"sd", "value":"Sindhi"},
            { "key":"se", "value":"Northern Sami"},
            { "key":"sm", "value":"Samoan"},
            { "key":"sg", "value":"Sango"},
            { "key":"sr", "value":"Serbian"},
            { "key":"gd", "value":"Scottish Gaelic; Gaelic"},
            { "key":"sn", "value":"Shona"},
            { "key":"si", "value":"Sinhala, Sinhalese"},
            { "key":"sk", "value":"Slovak"},
            { "key":"sl", "value":"Slovene"},
            { "key":"so", "value":"Somali"},
            { "key":"st", "value":"Southern Sotho"},
            { "key":"es", "value":"Spanish; Castilian"},
            { "key":"su", "value":"Sundanese"},
            { "key":"sw", "value":"Swahili"},
            { "key":"ss", "value":"Swati"},
            { "key":"sv", "value":"Swedish"},
            { "key":"ta", "value":"Tamil"},
            { "key":"te", "value":"Telugu"},
            { "key":"tg", "value":"Tajik"},
            { "key":"th", "value":"Thai"},
            { "key":"ti", "value":"Tigrinya"},
            { "key":"bo", "value":"Tibetan Standard, Tibetan, Central"},
            { "key":"tk", "value":"Turkmen"},
            { "key":"tl", "value":"Tagalog"},
            { "key":"tn", "value":"Tswana"},
            { "key":"to", "value":"Tonga (Tonga Islands)"},
            { "key":"tr", "value":"Turkish"},
            { "key":"ts", "value":"Tsonga"},
            { "key":"tt", "value":"Tatar"},
            { "key":"tw", "value":"Twi"},
            { "key":"ty", "value":"Tahitian"},
            { "key":"ug", "value":"Uighur, Uyghur"},
            { "key":"uk", "value":"Ukrainian"},
            { "key":"ur", "value":"Urdu"},
            { "key":"uz", "value":"Uzbek"},
            { "key":"ve", "value":"Venda"},
            { "key":"vi", "value":"Vietnamese"},
            { "key":"vo", "value":"Volapük"},
            { "key":"wa", "value":"Walloon"},
            { "key":"cy", "value":"Welsh"},
            { "key":"wo", "value":"Wolof"},
            { "key":"fy", "value":"Western Frisian"},
            { "key":"xh", "value":"Xhosa"},
            { "key":"yi", "value":"Yiddish"},
            { "key":"yo", "value":"Yoruba"},
            { "key":"za", "value":"Zhuang, Chuang"}
        ];
        this.get = function () {
            return languageCodes;
        }
    }]);
